### PR TITLE
[ng-bank-parser][ReadMe] Fix Typos

### PR DESCRIPTION
**Pull request by unicodeveloper**

### CODE REVIEW

**Comment by fathermerry** [comment]
Hey, thanks for this. The use of bank_key is intentional. That's cause it's different from bank_name. They key is the slug we use to identify the banks. So while for example the bank_name is Guaranty Trust Bank, the bank_key is GTB

**Comment by unicodeveloper** [comment]
I saw that, but after the parameters i discovered that you used `bank_name` while describing the key of the bank that will be passed as a parameter.  Am i right?. Then i saw `bank_name` as a key appearing in the result set. I think i should have just replaced the `bank_name` with `bank_key` in the description.

**Comment by fathermerry** [comment]
Absolutely. All the parameters should be bank_key. The bank_name in the result is the actually full bank name. Kindly update your pull request so I can merge. Thanks!

**Comment by unicodeveloper** [comment]
Check it out. I just updated it, Please let me know if there's something not rightly placed or positioned.

**Comment by fathermerry** [comment]
One last thing. In the API section, the parameter is bank_key

**Comment by unicodeveloper** [comment]
Aha!.Totally missed that, thanks for pointing it out. Fixed!

**Pull request merged**
